
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pranavkundra
 */
public class EnterPIN extends javax.swing.JPanel 
{
    JFrame frame;

    /**
     * Creates new form EnterPIN
     */
    public EnterPIN() 
    {
        initComponents();
        PIN_TextField.setHorizontalAlignment(PIN_TextField.CENTER);
        frame=null;
    }
    
    /**
     * Creates new form EnterPIN using parameterized constructor
     */
    public EnterPIN(JFrame frame) 
    {
        this.frame = frame;
        initComponents();
        PIN_TextField.setHorizontalAlignment(PIN_TextField.CENTER);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PIN_Label = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        AC_No_Label = new javax.swing.JLabel();
        AC_No_TextField = new javax.swing.JTextField();
        PIN_TextField = new javax.swing.JPasswordField();
        Reset_AC_No = new javax.swing.JButton();
        Reset_PIN = new javax.swing.JButton();
        Submit = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(500, 500));
        setLayout(new java.awt.GridBagLayout());

        PIN_Label.setText("Enter PIN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 4, 0);
        add(PIN_Label, gridBagConstraints);

        jButton1.setText("1");
        jButton1.setMaximumSize(new java.awt.Dimension(100, 29));
        jButton1.setPreferredSize(new java.awt.Dimension(76, 29));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        add(jButton1, gridBagConstraints);

        jButton2.setText("2");
        jButton2.setMaximumSize(new java.awt.Dimension(100, 29));
        jButton2.setPreferredSize(new java.awt.Dimension(76, 29));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        add(jButton2, gridBagConstraints);

        jButton3.setText("3");
        jButton3.setMaximumSize(new java.awt.Dimension(100, 29));
        jButton3.setPreferredSize(new java.awt.Dimension(76, 29));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        add(jButton3, gridBagConstraints);

        jButton4.setText("4");
        jButton4.setMaximumSize(new java.awt.Dimension(100, 29));
        jButton4.setPreferredSize(new java.awt.Dimension(76, 29));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        add(jButton4, gridBagConstraints);

        jButton5.setText("5");
        jButton5.setMaximumSize(new java.awt.Dimension(100, 29));
        jButton5.setPreferredSize(new java.awt.Dimension(76, 29));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        add(jButton5, gridBagConstraints);

        jButton6.setText("6");
        jButton6.setMaximumSize(new java.awt.Dimension(100, 29));
        jButton6.setPreferredSize(new java.awt.Dimension(76, 29));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        add(jButton6, gridBagConstraints);

        jButton7.setText("7");
        jButton7.setMaximumSize(new java.awt.Dimension(100, 29));
        jButton7.setPreferredSize(new java.awt.Dimension(76, 29));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        add(jButton7, gridBagConstraints);

        jButton8.setText("8");
        jButton8.setMaximumSize(new java.awt.Dimension(100, 29));
        jButton8.setPreferredSize(new java.awt.Dimension(76, 29));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        add(jButton8, gridBagConstraints);

        jButton0.setText("0");
        jButton0.setMaximumSize(new java.awt.Dimension(100, 29));
        jButton0.setPreferredSize(new java.awt.Dimension(76, 29));
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        add(jButton0, gridBagConstraints);

        jButton9.setText("9");
        jButton9.setMaximumSize(new java.awt.Dimension(100, 29));
        jButton9.setPreferredSize(new java.awt.Dimension(76, 29));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        add(jButton9, gridBagConstraints);

        AC_No_Label.setText("Enter Account Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        add(AC_No_Label, gridBagConstraints);

        AC_No_TextField.setText("Enter account number here...");
        AC_No_TextField.setMinimumSize(new java.awt.Dimension(195, 28));
        AC_No_TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AC_No_TextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                AC_No_TextFieldFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 37, 0);
        add(AC_No_TextField, gridBagConstraints);

        PIN_TextField.setEnabled(false);
        PIN_TextField.setMinimumSize(new java.awt.Dimension(60, 28));
        PIN_TextField.setPreferredSize(new java.awt.Dimension(100, 28));
        PIN_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PIN_TextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        add(PIN_TextField, gridBagConstraints);

        Reset_AC_No.setText("Reset");
        Reset_AC_No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset_AC_NoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 36, 0);
        add(Reset_AC_No, gridBagConstraints);

        Reset_PIN.setText("Reset");
        Reset_PIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset_PINActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 19, 0);
        add(Reset_PIN, gridBagConstraints);

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(47, 0, 0, 0);
        add(Submit, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        updatePIN(evt);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PIN_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PIN_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PIN_TextFieldActionPerformed

    private void AC_No_TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AC_No_TextFieldFocusGained
        // TODO add your handling code here:
        if(AC_No_TextField.getText().trim().equals("Enter account number here..."))
            AC_No_TextField.setText("");
    }//GEN-LAST:event_AC_No_TextFieldFocusGained

    private void AC_No_TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AC_No_TextFieldFocusLost
        // TODO add your handling code here:
        if(AC_No_TextField.getText().trim().equals(""))
            AC_No_TextField.setText("Enter account number here...");
        
        else if(!AC_No_TextField.getText().trim().matches("[0-9]+"))
        {
            JOptionPane.showMessageDialog(frame, "Please enter only a numerical account number");
            AC_No_TextField.setText("Enter account number here...");
        }
    }//GEN-LAST:event_AC_No_TextFieldFocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        updatePIN(evt);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        updatePIN(evt);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        updatePIN(evt);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        updatePIN(evt);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        updatePIN(evt);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        updatePIN(evt);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        updatePIN(evt);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        updatePIN(evt);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        // TODO add your handling code here:
        updatePIN(evt);
    }//GEN-LAST:event_jButton0ActionPerformed

    private void Reset_AC_NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset_AC_NoActionPerformed
        // TODO add your handling code here:
        AC_No_TextField.setText("Enter account number here...");
    }//GEN-LAST:event_Reset_AC_NoActionPerformed

    private void Reset_PINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset_PINActionPerformed
        // TODO add your handling code here:
        PIN_TextField.setText("");
    }//GEN-LAST:event_Reset_PINActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        try
        {
            Data data = new Data();
            String pin = data.getPIN(AC_No_TextField.getText());
            
            if(pin.equals("InvalidPIN"))
                JOptionPane.showMessageDialog(frame, "Invalid Account Number");
            
            else if(pin.equals(new String(PIN_TextField.getPassword())))
            {
                frame.setContentPane(new Menu(frame, AC_No_TextField.getText()));
                frame.invalidate();
                frame.validate();
            }
            
            else
                JOptionPane.showMessageDialog(frame, "PIN incorrect!");
        }
        catch(FileNotFoundException e) {}
        catch(IOException e) {}
    }//GEN-LAST:event_SubmitActionPerformed

    private void updatePIN(java.awt.event.ActionEvent evt)
    {
        JButton button = (JButton)(evt.getSource());
        String append_value = button.getText();
        String current_pin = new String(PIN_TextField.getPassword());
        PIN_TextField.setText(current_pin + append_value);
//        System.out.println(current_pin+append_value);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AC_No_Label;
    private javax.swing.JTextField AC_No_TextField;
    private javax.swing.JLabel PIN_Label;
    private javax.swing.JPasswordField PIN_TextField;
    private javax.swing.JButton Reset_AC_No;
    private javax.swing.JButton Reset_PIN;
    private javax.swing.JButton Submit;
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables
}
